const express = require('express');
const { chromium } = require('playwright');
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const app = express();
app.use(express.json({ limit: '15mb' }));

const TEMPLATES = {
  lifestyle: fs.readFileSync(path.join(__dirname, 'templates', 'lifestyle.html'), 'utf8'),
  highlight: fs.readFileSync(path.join(__dirname, 'templates', 'highlight.html'), 'utf8'),
  pricecard: fs.readFileSync(path.join(__dirname, 'templates', 'pricecard.html'), 'utf8'),
};

const SIZE = { width: 1080, height: 1350 };

function escapeHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Replaces every {{key}} in the template with data[key]. photoDataUri and
// *Color values are generated by us (never user text), so they go in raw;
// everything else is HTML-escaped since it's real-estate copy that can
// contain "&", quotes, etc.
function fillTemplate(html, data) {
  return html.replace(/\{\{(\w+)\}\}/g, (match, key) => {
    if (!(key in data) || data[key] == null) return '';
    if (key === 'photoDataUri' || /Color$/i.test(key)) return data[key];
    return escapeHtml(data[key]);
  });
}

function detectMime(buffer) {
  if (buffer[0] === 0xff && buffer[1] === 0xd8) return 'image/jpeg';
  if (buffer[0] === 0x89 && buffer[1] === 0x50) return 'image/png';
  if (buffer.slice(0, 4).toString('ascii') === 'RIFF') return 'image/webp';
  return 'image/jpeg';
}

function rgbToHsl(r, g, b) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h, s;
  const l = (max + min) / 2;
  if (max === min) {
    h = s = 0;
  } else {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      default: h = (r - g) / d + 4;
    }
    h /= 6;
  }
  return [h, s, l];
}

function hslToRgb(h, s, l) {
  let r, g, b;
  if (s === 0) {
    r = g = b = l;
  } else {
    const hue2rgb = (p, q, t) => {
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q;
      if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
      return p;
    };
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    r = hue2rgb(p, q, h + 1 / 3);
    g = hue2rgb(p, q, h);
    b = hue2rgb(p, q, h - 1 / 3);
  }
  return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

function rgbToHex(r, g, b) {
  return '#' + [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('');
}

// Pulls a deep, brand-appropriate pillarbox color out of the photo itself
// (average color, pushed toward a moody saturation/lightness range) instead
// of using one fixed brand color for every post.
async function extractBarColor(buffer) {
  const { data } = await sharp(buffer).resize(1, 1).raw().toBuffer({ resolveWithObject: true });
  const [r, g, b] = data;
  let [h, s, l] = rgbToHsl(r, g, b);
  s = Math.min(Math.max(s, 0.25), 0.55);
  l = Math.min(Math.max(l, 0.16), 0.30);
  const [nr, ng, nb] = hslToRgb(h, s, l);
  return rgbToHex(nr, ng, nb);
}

let browserPromise;
function getBrowser() {
  if (!browserPromise) {
    browserPromise = chromium.launch({ args: ['--no-sandbox'] });
  }
  return browserPromise;
}

app.post('/render', async (req, res) => {
  try {
    const { template, photoBase64, pillarboxColor: overrideColor, ...fields } = req.body || {};

    if (!template || !TEMPLATES[template]) {
      return res.status(400).json({ error: `Unknown template "${template}". Use lifestyle | highlight | pricecard.` });
    }
    if (!photoBase64) {
      return res.status(400).json({ error: 'photoBase64 is required (base64 string, no data: prefix)' });
    }

    const buffer = Buffer.from(photoBase64, 'base64');
    const mime = detectMime(buffer);
    const photoDataUri = `data:${mime};base64,${photoBase64}`;

    let pillarboxColor = overrideColor;
    if (!pillarboxColor && template !== 'lifestyle') {
      pillarboxColor = await extractBarColor(buffer);
    }

    const html = fillTemplate(TEMPLATES[template], {
      accentGold: '#F5E1B8',
      website: 'www.ngiproperty.com',
      phone: '+20 122 444 9009',
      ...fields,
      photoDataUri,
      pillarboxColor,
    });

    const browser = await getBrowser();
    const page = await browser.newPage({ viewport: SIZE });
    await page.setContent(html, { waitUntil: 'networkidle', timeout: 15000 });
    const png = await page.screenshot({ type: 'png' });
    await page.close();

    res.set('Content-Type', 'image/png');
    res.send(png);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

app.get('/health', (_req, res) => res.json({ ok: true }));

const PORT = process.env.PORT || 3500;
app.listen(PORT, () => console.log(`ngi-render listening on :${PORT}`));
